In [2]:
import pandas as pd
import numpy as np

In [3]:
rates = pd.read_csv('/Users/jiangxiaoyu/Desktop/All Projects/Scalable_LVMOGP/data/exchange/exchange_rates.csv')
train = pd.read_csv('/Users/jiangxiaoyu/Desktop/All Projects/Scalable_LVMOGP/data/exchange/exchange_train.csv')
test = pd.read_csv('/Users/jiangxiaoyu/Desktop/All Projects/Scalable_LVMOGP/data/exchange/exchange_test.csv')

In [4]:
# we are interested in USD/CAD	;  USD/JPY  ;  USD/AUD

In [8]:
train.isna().sum()

year         0
USD/CHF      0
USD/EUR      0
USD/GBP      0
USD/HKD      0
USD/KRW      0
USD/MXN      0
USD/NZD      0
USD/XAG      8
USD/XAU      9
USD/XPT     42
USD/CAD     51
USD/JPY    101
USD/AUD    151
dtype: int64

In [6]:
train.index[train['USD/XAU'].isna()]

Index([0, 68, 88, 102, 131, 165, 247, 249, 250], dtype='int64')

In [7]:
(rates - rates.mean()) / rates.std()

,year,USD/CHF,USD/EUR,USD/GBP,USD/HKD,USD/KRW,USD/MXN,USD/NZD,USD/XAG,USD/XAU,USD/XPT,USD/CAD,USD/JPY,USD/AUD
0,-1.699044,-0.342639,-0.778051,-0.707256,1.049742,0.384535,1.252689,-0.845319,NaN,NaN,NaN,-1.185898,-0.295867,-1.037143
1,-1.689536,-0.686024,-0.998590,-1.305463,0.717495,0.281162,1.361630,-0.944758,-0.649272,-0.914379,-2.005875,-1.242879,-0.496650,-1.147849
2,-1.680028,-0.811902,-1.141424,-1.451347,0.630919,-0.255069,0.513864,-1.166316,-1.043177,-1.156267,-2.093723,-1.319596,-0.417166,-1.281456
3,-1.670520,-0.936741,-1.309645,-1.799110,0.515547,-0.526780,-0.301969,-1.493876,-0.934547,-1.490407,-2.181721,-1.306122,-0.288092,-1.434024
4,-1.641995,-0.917227,-1.275612,-1.600177,0.337820,-0.918177,-0.390803,-1.470708,-1.600110,-1.490407,-2.181721,-1.330803,-0.210125,-1.395365
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
246,1.657337,1.145557,1.238264,-0.465488,0.045179,-1.149089,0.861009,0.876567,1.225046,2.008200,2.168971,1.100087,1.017078,0.653930
247,1.685862,1.139986,1.327649,-0.612413,-0.179986,-0.995277,0.935748,0.950208,NaN,NaN,NaN,1.215591,0.876856,0.782619
248,1.714386,1.589002,1.689992,-0.277605,0.016419,-1.137425,0.472716,1.037013,1.741276,2.329798,2.476534,1.311813,1.000186,0.950399
249,1.723894,1.986049,1.905095,-0.216341,-0.146468,-0.718481,0.234801,1.118978,NaN,NaN,NaN,1.353876,1.306980,0.866179
250,1.752419,1.816784,1.691593,-0.452541,0.150669,-0.652705,0.071458,0.970045,1.863329,NaN,NaN,1.199668,1.657748,0.954158